In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [ ]:
pd.set_option("display.max_columns", None)

In [ ]:
sns.set_style("whitegrid")

In [17]:
df = pd.read_csv("german_credit_data.csv")

In [18]:
df.head()

  ,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0     0,67,male,2,own,NA,little,1169,6,radio/TV,good
1  1,22,female,2,own,little,moderate,5951,48,radi...
2   2,49,male,1,own,little,NA,2096,12,education,good
3  3,45,male,2,free,little,little,7882,42,furnitu...
4     4,53,male,2,free,little,little,4870,24,car,bad

In [19]:
df = pd.read_csv("german_credit_data.csv")
df = df.reset_index().rename(columns={"index": "Unnamed: 0"})

In [20]:
df.head()

,Unnamed: 0,",Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk"
0,0,"0,67,male,2,own,NA,little,1169,6,radio/TV,good"
1,1,"1,22,female,2,own,little,moderate,5951,48,radi..."
2,2,"2,49,male,1,own,little,NA,2096,12,education,good"
3,3,"3,45,male,2,free,little,little,7882,42,furnitu..."
4,4,"4,53,male,2,free,little,little,4870,24,car,bad"

In [1]:
df["age"].describe()

NameError: name 'df' is not defined